### ISSUE TITLE
Question for how to write ml_planner.yaml  in submitting process

### ISSUE THREAD

**Issue by YangYangLeo** [motional/nuplan-devkit#302]
Hello,
Could you please tell me what should I write for "model_config“ if I want to submit my own ml_planner?

![Screenshot from 2023-05-13 17-05-39](https://github.com/motional/nuplan-devkit/assets/94044472/c31e5da3-7a0d-476b-a1c4-db7aea6e1cde)

I just type to "go_model" like the picture above.

But I got "validation_challenge99.log
2023-05-13 14:15:39,072 : ERROR : Planner initialization failed!
2023-05-13 14:15:44,421 : ERROR : Planner initialization failed!" issue after submitting image.

I am wondering if this issue is related to the"model_config" ?
If so, could you please tell me a suggestion?Thanks a lot.

BTW here is my id:
{"submitted_image_uri": "937891341272.dkr.ecr.us-east-1.amazonaws.com/nuplan-planning-challenge-1856-participant-team-20954:83cee015-17ba-4524-9e75-0ebcfedeb3a2"}

**Comment by patk-motional** [comment]
Hi @YangYangLeo,

Try without the `'` around go_model.

**Comment by patk-motional** [comment]
You can try a few more methods:

### 1.
Revert [ml_planner.yaml](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/simulation/planner/ml_planner.yaml) to the original. It should look like this:
```
ml_planner:
  _target_: nuplan.planning.simulation.planner.ml_planner.ml_planner.MLPlanner
  _convert_: 'all'

  model_config: ???  # Dictionary key from existing planner model config (e.g. raster_model)
  checkpoint_path: ???  # Path to trained model checkpoint
```
In [entrypoint_submission.py](https://github.com/motional/nuplan-devkit/blob/master/nuplan/entrypoint_submission.sh)
```
conda run -n nuplan --no-capture-output python -u nuplan/planning/script/run_submission_planner.py output_dir=/tmp/ model=YOUR_MODEL planner=ml_planner planner.ml_planner.model_config=\${model} planner.ml_planner.checkpoint_path="YOUR_CHECKPOINT"
```
replace `YOUR_PLANNER` and `YOUR_CHECKPOINT`.
### 2. 
Modify [ml_planner.yaml](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/simulation/planner/ml_planner.yaml). It should look like this:
```
ml_planner:
  _target_: nuplan.planning.simulation.planner.ml_planner.ml_planner.MLPlanner
  _convert_: 'all'

  model_config: ???  # Dictionary key from existing planner model config (e.g. raster_model)
  checkpoint_path: "YOUR_CHECKPOINT"  # Path to trained model checkpoint
```
In [entrypoint_submission.py](https://github.com/motional/nuplan-devkit/blob/master/nuplan/entrypoint_submission.sh)
```
conda run -n nuplan --no-capture-output python -u nuplan/planning/script/run_submission_planner.py output_dir=/tmp/ model=YOUR_MODEL planner=ml_planner planner.ml_planner.model_config=\${model}
```
replace `YOUR_PLANNER` and `YOUR_CHECKPOINT`.

### 3. 
Modify [default_common.py](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/common/default_common.yaml)
```
# Default common configs

defaults:
  # Add common items
  - scenario_builder: nuplan_mini
  - scenario_filter: one_continuous_log
  - model: YOUR_MODEL
  # Worker that is used to run simulations
  - worker: ray_distributed
```
Modify [ml_planner.yaml](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/simulation/planner/ml_planner.yaml) to the original. It should look like this:
```
ml_planner:
  _target_: nuplan.planning.simulation.planner.ml_planner.ml_planner.MLPlanner
  _convert_: 'all'

  model_config: ${model}  # Dictionary key from existing planner model config (e.g. raster_model)
  checkpoint_path: "YOUR_CHECKPOINT"  # Path to trained model checkpoint
```
In [entrypoint_submission.py](https://github.com/motional/nuplan-devkit/blob/master/nuplan/entrypoint_submission.sh)
```
conda run -n nuplan --no-capture-output python -u nuplan/planning/script/run_submission_planner.py output_dir=/tmp/ planner=ml_planner
```
replace `YOUR_PLANNER` and `YOUR_CHECKPOINT`.
